export const terms = {
    username: "User Name",
    signIn: "Sign In",
    confirmPassword: "Confirm Password",
    signUp: "Sign Up",
    doesNotMatchPassword: "doesn't match password",
    password: 'password',
    updateInfo: "Update Info",
    changePassword: "Change Password",
    hello: "Hello",
    invalidOperation: "Invalid Operation",
    admin: 'admin',
    yes: 'Yes',
    no: 'No',
    ok: 'Ok',
    areYouSureYouWouldLikeToDelete: "Are you sure you would like to delete",
    cancel: 'Cancel',
    home: 'Home',
    userAccounts: 'User Accounts',
    invalidSignIn: "Invalid Sign In Info",
    signOut: 'Sign Out',
    resetPassword: 'Reset Password',
    passwordDeletedSuccessful: "Password Deleted",
    passwordDeleteConfirmOf: "Are you sure you want to delete the password of",
    rememberOnThisDevice: "Remember on this device?",
    cantDeleteTheLastAdminUser: "Can't delete the last admin user",
    shouldResetPassword: "Reset Password?",
    passwordDeleted: "Password was reset, next time the user signs in, a new password will be determined",
    delete: "Delete",
    save:"Save",
    phoneNumber: "Phone Number",
    organization: "Organization",
    superUser: "Super User",
    organizationName: "Organization Name",
    organizationDescription: "Organization Description",
    contactName: "Contact Name",
    contactEmail: "Contact Email",
    contactPhoneNumber: "`Contact Phone Number",
    taskAddedBy: "Added By",
    taskDescription: "Task Description",
    taskTitle: "Task Title",
    sourceAddress: "Source Address",
    destinationAddress: "Destination Address",
    isFitInElevator: "Fits in an Elevator",
    destinationFloor: "Destination Floor",
    sourceFloor: "Source Floor",
    taskExternalRemarks: "Task Remarks",
    taskInternalRemarks: "Task Internal Remarks",
    taskRewardPoints: "Task Reward Points",
    pickUpPossibleTimes: "Pick Up Possible Times",
    dropOffPossibleTimes: "Drop Off Possible Times",
    vehicleType: "Vehicle Type",
    pickUpContactName: "Pick Up Contact Name",
    pickUpContactPhone: "Pick Up Contact Phone",
    dropOffContactName: "Drop Off Contact Name",
    dropOffContactPhone: "Drop Off Contact Phone",
    taskStatus: "Status",
    assignedTo: "Assigned To"
}
